### ISSUE TITLE
failing fast

### ISSUE THREAD

**Issue by charleshansen** [cloudfoundry/exemplar-release#4]
Let's say I have a manifest with multiple configuration options that are easy to get wrong. For example, one of the properties must be from a specific set of strings, say ["foo", "bar", "baz"], but an operator might be confused and put in "potato"

- If an operator deploys with the invalid "potato" value, it will roll a canary VM, restart the job, and then fail. This takes a while, and now the canary VM is broken. The operator is angry.

- It would be great if this failed before any VMs are rolled, but I think the only available hook is compiling the templates. Now I need complicated and untested ERB logic.

Is there a non-terrible way to validate my manifest before rolling VMs? 

If your answer is "better documentation", I've tried that. I find users do not read detailed documentation until they are already angry at us, and even then it is iffy.

**Comment by wendorf** [comment]
The first thing I thought of was shelling out to another script in the package inside of the erb: `<% system( "./validate-config.rb", p ) %>`, but this is pretty outside of the contract of BOSH template rendering, so is probably something to avoid.

It seems like in this case, having that logic in your template is probably the best answer. At that point, you would want to test it and that's definitely not well-trodden territory. I wonder if exemplar-release could have a canonical "good property validator" template with a corresponding test.

Ideally, I'd like to see BOSH extend the lifecycle with a config-validation hook during that early part of the lifecycle. @cppforlife do you have any thoughts around this?

**Comment by cppforlife** [comment]
inline

Sent from my iPhone

> On May 1, 2017, at 1:57 PM, Dan Wendorf <notifications@github.com> wrote:
> 
> The first thing I thought of was shelling out to another script in the package inside of the erb: <% system( "./validate-config.rb", p ) %>, but this is pretty outside of the contract of BOSH template rendering, so is probably something to avoid.
> 
> It seems like in this case, having that logic in your template is probably the best answer. At that point, you would want to test it and that's definitely not well-trodden territory. I wonder if exemplar-release could have a canonical "good property validator" template with a corresponding test.
> 
> Ideally, I'd like to see BOSH extend the lifecycle with a config-validation hook during that early part of the lifecycle. @cppforlife do you have any thoughts around this?
> 
erb rendering _is_ the stage that should be doing that validation. it would be nice to spend a lil time on improving bosh template gem to make it easier to test erbs

**Comment by charleshansen** [comment]
@wendorf I would love a canonical good property validator. There are stories of teams spending many days trying to write and test one and then giving up in failure. I'd rather not add myself to that list of cautionary tales.
