### ISSUE TITLE
RabbitMQ release uses 'post-deploy'. Shouldn't update the README?

### ISSUE THREAD

**Issue by bgandon** [cloudfoundry/exemplar-release#9]
Hi @xoebus & all,

I'm in the process of reviewing this `exemplar-release` documentation before contributing additions here, like examples of BPM jobs (a donation from the training courses delivered by my company **Gstack**), and correct drain scripts for cluster 'scale-in' condition, i.e. permanent removal of stateful cluster members.

About `post-deploy`, I recently saw that [the RabbitMQ release uses a `post-deploy` script](https://github.com/pivotal-cf/cf-rabbitmq-release/blob/master/jobs/rabbitmq-server/templates/post-deploy.bash). In the best-practice here, it's [currently said](https://github.com/cloudfoundry/exemplar-release#post-deploy-docs) that `post-deploy` is more or less a useless concept.

In the RabbitMQ release, it is supposed to run checks at the _cluster_ scale. I say “supposed” because if you dig into the (unfortunately messy) code, you'll find out it only checks the current node health.

Anyway, I found out an example of a `post-deploy` script!

Questions:
- Shouldn't we update the README here about that?
- What would you say as a practice, about double-checking in a `post-deploy` script that state has converged at a cluster scale?

Best,

**Comment by xoebus** [comment]
We mention that it "may be useful for checking the health of an entire deployment" in the document. It sounds as if the RabbitMQ release has a bug if it's only checking the current node? If this doesn't need to be `post-deploy` and can instead be `post-start` then I don't think we should point it out as a good usage of the `post-deploy` feature. Maybe the entire Rabbit cluster needs to be running before a single node can be checked?
